import React, { Component } from 'react';
import { connect } from 'react-redux';
import TaskDisplay from './TaskDisplay';
import TaskToAdd from './TaskToAdd';

import { addTask, deleteTask, updateTask } from '../redux/actions';

//Top level presentaitonal component
class CrudView extends Component {

    render() {

        return (
            <div className="container">
                <p>Current Tasks Board</p>
                <p>Simple CRUD using the MERN stack. Refresh the page. It is saved to the server running Node.js and MongoDB on Heroku.
                UI is ReactJS.</p>
                <ul>
                    <li><a href="https://github.com/KamiMoon/angular_full/blob/master/client/app/crud/crud.controller.js">AngularJS client</a>            using <a href="https://github.com/KamiMoon/angular_full/blob/master/client/app/task/task.service.js">$resource</a>
                    </li>
                    <li><a href="https://github.com/KamiMoon/angular_full/blob/master/server/api/task/task.controller.js">Node.js contoller using Express</a></li>
                    <li><a href="https://github.com/KamiMoon/angular_full/blob/master/server/api/task/task.model.js">MongoDB using Mongoose</a></li>
                </ul>
                <table className="table table-responsive">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Worked (hrs)</th>
                            <th>Estimated (hrs)</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {this.props.tasks.map((task, index) => {
                            return (
                                <TaskDisplay key={task.name} task={task}
                                    deleteTask={this.props.deleteTask}
                                    saveTask={this.props.updateTask}
                                />
                            );
                        })}
                        <TaskToAdd addTask={this.props.addTask} />
                    </tbody>
                </table>
            </div>
        );
    }
}



const mapStateToProps = state => {
    return {
        tasks: state.tasks
    }
}
const mapDispatchToProps = dispatch => {
    return {
        addTask: task => {
            dispatch(addTask(task))
        },
        updateTask: task => {
            dispatch(updateTask(task))
        },
        deleteTask: task => {
            dispatch(deleteTask(task))
        }
    }
}

//Container Component generated by react-redux
//No presentation, but has the map dispatch functions
//Child is CrudView above
const Crud = connect(
    mapStateToProps,
    mapDispatchToProps
)(CrudView)

export default Crud;