import { connect } from 'react-redux';
import { withRouter } from 'react-router-dom';

import { addTask, deleteTask, updateTask, getTasks } from './redux/crudActions';
import CrudView from './CrudView';

const mapStateToProps = state => {
    return {
        crud: state.crud
    }
}
const mapDispatchToProps = dispatch => {
    return {
        getTasks: () => {
            dispatch(getTasks())
        },
        addTask: task => {
            dispatch(addTask(task))
        },
        updateTask: task => {
            dispatch(updateTask(task))
        },
        deleteTask: task => {
            dispatch(deleteTask(task))
        }
    }
}

//Container Component generated by react-redux
//No presentation, but has the map dispatch functions
//Child is CrudView
const CrudContainer = withRouter(connect(
    mapStateToProps,
    mapDispatchToProps
)(CrudView))

export default CrudContainer;